"""
Fine-tuning Pipeline for First Impression Vision Model.

Trains a lightweight vision model (EfficientNet-B3 backbone) on synthetic labels
generated by Claude Vision. Exports to ONNX for production inference.

Requirements: pip install torch torchvision timm scikit-learn onnx onnxruntime
"""
from __future__ import annotations

import argparse
import json
import logging
from pathlib import Path
from typing import Optional

import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader, random_split
from PIL import Image
import torchvision.transforms as T

try:
    import timm
    HAS_TIMM = True
except ImportError:
    HAS_TIMM = False

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
logger = logging.getLogger(__name__)

# ──────────────────────────────────────────────────────────────────────
# Dataset
# ──────────────────────────────────────────────────────────────────────

TARGETS = ["trustworthiness", "attractiveness", "confidence"]

TRAIN_TRANSFORMS = T.Compose([
    T.Resize(256),
    T.CenterCrop(224),
    T.RandomHorizontalFlip(),
    T.ColorJitter(brightness=0.15, contrast=0.15, saturation=0.1),
    T.RandomRotation(8),
    T.ToTensor(),
    T.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225]),
])

VAL_TRANSFORMS = T.Compose([
    T.Resize(256),
    T.CenterCrop(224),
    T.ToTensor(),
    T.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225]),
])


class FaceImpressionsDataset(Dataset):
    def __init__(self, labels_path: Path, transform=None, root_dir: Optional[Path] = None):
        self.records = []
        self.transform = transform
        self.root_dir = root_dir

        with open(labels_path) as f:
            for line in f:
                rec = json.loads(line.strip())
                # Validate required fields
                if all(k in rec for k in ["image_path"] + TARGETS):
                    self.records.append(rec)

        logger.info(f"Loaded {len(self.records)} valid records from {labels_path}")

    def __len__(self):
        return len(self.records)

    def __getitem__(self, idx: int):
        rec = self.records[idx]
        img_path = Path(rec["image_path"])
        if self.root_dir and not img_path.is_absolute():
            img_path = self.root_dir / img_path

        img = Image.open(img_path).convert("RGB")
        if self.transform:
            img = self.transform(img)

        # Normalize scores to [0, 1]
        labels = torch.tensor(
            [rec[t] / 100.0 for t in TARGETS],
            dtype=torch.float32,
        )
        return img, labels


# ──────────────────────────────────────────────────────────────────────
# Model
# ──────────────────────────────────────────────────────────────────────

class FirstImpressionModel(nn.Module):
    """EfficientNet-B3 backbone → 3-head regression (trust, attract, conf)."""

    def __init__(self, pretrained: bool = True, dropout: float = 0.3):
        super().__init__()
        if not HAS_TIMM:
            raise ImportError("Install timm: pip install timm")

        self.backbone = timm.create_model(
            "efficientnet_b3",
            pretrained=pretrained,
            num_classes=0,  # headless
        )
        feat_dim = self.backbone.num_features

        self.head = nn.Sequential(
            nn.Dropout(dropout),
            nn.Linear(feat_dim, 256),
            nn.GELU(),
            nn.Dropout(dropout / 2),
            nn.Linear(256, len(TARGETS)),
            nn.Sigmoid(),  # output in [0, 1]
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        features = self.backbone(x)
        return self.head(features)


# ──────────────────────────────────────────────────────────────────────
# Training
# ──────────────────────────────────────────────────────────────────────

def train_epoch(model, loader, criterion, optimizer, device) -> float:
    model.train()
    total_loss = 0.0
    for imgs, labels in loader:
        imgs, labels = imgs.to(device), labels.to(device)
        optimizer.zero_grad()
        preds = model(imgs)
        loss = criterion(preds, labels)
        loss.backward()
        optimizer.step()
        total_loss += loss.item() * len(imgs)
    return total_loss / len(loader.dataset)


@torch.no_grad()
def eval_epoch(model, loader, criterion, device) -> tuple[float, float]:
    model.eval()
    total_loss = 0.0
    all_preds, all_labels = [], []

    for imgs, labels in loader:
        imgs, labels = imgs.to(device), labels.to(device)
        preds = model(imgs)
        loss = criterion(preds, labels)
        total_loss += loss.item() * len(imgs)
        all_preds.append(preds.cpu())
        all_labels.append(labels.cpu())

    all_preds = torch.cat(all_preds)
    all_labels = torch.cat(all_labels)
    mae = (all_preds - all_labels).abs().mean().item() * 100  # back to 0-100 scale

    return total_loss / len(loader.dataset), mae


def export_onnx(model: nn.Module, output_path: Path, device: torch.device) -> None:
    model.eval()
    dummy = torch.randn(1, 3, 224, 224).to(device)
    torch.onnx.export(
        model,
        dummy,
        str(output_path),
        input_names=["image"],
        output_names=["scores"],
        dynamic_axes={"image": {0: "batch"}, "scores": {0: "batch"}},
        opset_version=17,
    )
    logger.info(f"ONNX model exported → {output_path}")


def main():
    parser = argparse.ArgumentParser(description="Fine-tune First Impression vision model")
    parser.add_argument("--labels", type=Path, required=True, help="JSONL labels file from synthetic_labeling.py")
    parser.add_argument("--output-dir", type=Path, default=Path("checkpoints"), help="Where to save model")
    parser.add_argument("--epochs", type=int, default=30)
    parser.add_argument("--batch-size", type=int, default=32)
    parser.add_argument("--lr", type=float, default=3e-4)
    parser.add_argument("--val-split", type=float, default=0.15)
    parser.add_argument("--no-pretrained", action="store_true")
    args = parser.parse_args()

    device = torch.device("mps" if torch.backends.mps.is_available() else "cuda" if torch.cuda.is_available() else "cpu")
    logger.info(f"Using device: {device}")

    args.output_dir.mkdir(parents=True, exist_ok=True)

    # Dataset splits
    full_dataset = FaceImpressionsDataset(args.labels, transform=TRAIN_TRANSFORMS)
    val_size = int(len(full_dataset) * args.val_split)
    train_size = len(full_dataset) - val_size
    train_ds, val_ds = random_split(full_dataset, [train_size, val_size])
    val_ds.dataset.transform = VAL_TRANSFORMS

    train_loader = DataLoader(train_ds, batch_size=args.batch_size, shuffle=True, num_workers=4, pin_memory=True)
    val_loader = DataLoader(val_ds, batch_size=args.batch_size, shuffle=False, num_workers=4, pin_memory=True)

    logger.info(f"Train: {train_size} | Val: {val_size}")

    # Model, loss, optimizer
    model = FirstImpressionModel(pretrained=not args.no_pretrained).to(device)
    criterion = nn.HuberLoss(delta=0.1)
    optimizer = optim.AdamW(model.parameters(), lr=args.lr, weight_decay=1e-4)
    scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=args.epochs)

    best_val_mae = float("inf")
    for epoch in range(1, args.epochs + 1):
        train_loss = train_epoch(model, train_loader, criterion, optimizer, device)
        val_loss, val_mae = eval_epoch(model, val_loader, criterion, device)
        scheduler.step()

        logger.info(
            f"Epoch {epoch:03d}/{args.epochs} | "
            f"train_loss={train_loss:.4f} val_loss={val_loss:.4f} val_mae={val_mae:.2f}"
        )

        if val_mae < best_val_mae:
            best_val_mae = val_mae
            ckpt_path = args.output_dir / "best_model.pt"
            torch.save(model.state_dict(), ckpt_path)
            logger.info(f"  ✓ New best MAE={val_mae:.2f} → saved {ckpt_path}")

    # Export final ONNX
    model.load_state_dict(torch.load(args.output_dir / "best_model.pt", map_location=device))
    export_onnx(model, args.output_dir / "first_impression.onnx", device)

    logger.info(f"Training complete. Best val MAE: {best_val_mae:.2f}/100")


if __name__ == "__main__":
    main()
